name = "kalajawi"
main = "dist/server/_worker.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./dist/client"

[build]
command = "npm run build"

[vars]
ENVIRONMENT = "production"

[[rules]]
type = "js"
globs = ["**/*.js"]
fallthrough = true

[[rules]]
type = "wasm"
globs = ["**/*.wasm"]
fallthrough = true
