name = "kalajawi"
main = ".output/server/index.mjs"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
no_bundle = true

[vars]
ENVIRONMENT = "production"

[assets]
directory = ".output/public"

[[rules]]
type = "ESModule"
globs = ["**/*.mjs", "**/*.js"]
